### ISSUE TITLE
Unable to obtain the Wii's bluetooth MAC address

### ISSUE THREAD

**Issue by skadge** [rnconrad/WiimoteEmulator#1]
After carefully following the suggested procedure to obtain the Wii BT MAC address (including double-checking that the Bluetooth adapter has the same MAC address as the WiiMote), I'm still not able to get the Wii MAC address via `hcidump`.

In the `README`, you seem to suggest that other options are possible. Could you elaborate? Could your unplished tool `wiimitm` help with that as well?

Thanks!

**Comment by rnconrad** [comment]
The battery method is tricky -- it seems to only work intermittently and when the conditions are just right.

Another way to determine the Wii's address is to use a Bluetooth sniffer, e.g. Ubertooth One. Also, you can install an application on your (soft-modded) Wii, e.g. some distro of homebrew or Linux, that can tell you information about the Bluetooth adapter in the Wii. If you don't mind opening up the Wii's hardware, you can actually connect the Wii's Bluetooth module to your PC via USB and find its address like a normal adapter. The relative complexity of these methods is the reason I recommend trying the battery method, as it can save you a lot of time and effort if you can get it to work.

The wiimitm application won't be helpful here unfortunately. It is a debugging tool that connects to a Wii and a Wiimote and forwards packets between them, printing everything that is sent to effectively eavesdrop on a normal Wiimote connection. It was originally intended to do more than that, but was never quite finished and thus was excluded from the repo. I may clean it up and include it at some point.

It's worth noting that I have been working on a fork of this that involves reverse engineering the Wii's Bluetooth module and could help determine how to sync the emulator properly with a Wii. I will have another look soon and see if there could be a new way to get around needing the Wii's address altogether.

**Comment by skadge** [comment]
@rnconrad Thanks for your detailed answer! In case someone is wondering how to plug the Wii bluetooth adapter into a PC, [here are the explanations](https://forums.dolphin-emu.org/Thread-how-to-wire-a-wii-s-bluetooth-module-to-a-pc-usb-port). The guide to open the Wii and access the adapter is [there (iFixIt)](https://www.ifixit.com/Guide/Nintendo+Wii+Bluetooth+Board+Replacement/3456). No exactly easy, though :-/

**Comment by skadge** [comment]
Alright, as a follow-up: so far, the easiest way I found to reliably determine the Wii bluetooth address consist indeed in soft-modding the Wii -- it actually only requires a SD card, takes only a few minutes, and does not impact the normal working of the console.

The steps I followed are:
- install the HomeBrew channel (following for instance [these instructions](https://gbatemp.net/threads/how-to-softmod-a-wii-and-play-backup-wii-gamecube-and-wiiware-games.360687/)
- install [GeeXbox](http://www.wiibrew.org/wiki/GeeXboX) on the same SD card: simply download the archive and extract it onto the homebrew SD card root.
- go to the HomeBrew channel, start GeeXbox
- in GeeXbox, go to Options to start the Obex Bluetooth filesharing
- from another computer, scan for bluetooth devices (`hcitool scan`), you should see the Wii!

Closing the issue.
