### ISSUE TITLE
wmemulator can't write new device address, even with sudo

### ISSUE THREAD

**Issue by Freddi-Marco** [rnconrad/WiimoteEmulator#28]
Sorry to take, your time, but it's two days that i was trying to get it working, but i always get this log after starting the program:
```
Unsupported manufacturer
Failed to set device address
Device manufacturer: Atheros Communications, Inc. (69)
Failed to set device address
Warning: device address must have a Nintendo OUI
```
I've even tried running it with sudo access, but it shows up too. To be clear, i'm using the [JRogaishio](https://github.com/JRogaishio) fork of the project, with the graceful_connect error fixed, and i'm running the program without no arguments.

**Comment by Freddi-Marco** [comment]
I thing i forgot, the program actually starts after and says that it is waiting for connections, but pressing the sync button on the wiiu (using Wii mode) doesn't do nothing

**Comment by Freddi-Marco** [comment]
After some testing, i did manage to connect it to the console (even in WiiU mode!) which is very cool.
For anyone who struggles connecting it, try syncing it up in wiiu mode instead of vWii.

**Comment by purplebar0** [comment]
> After some testing, i did manage to connect it to the console (even in WiiU mode!) which is very cool. For anyone who struggles connecting it, try syncing it up in wiiu mode instead of vWii.

Do you remember if you had to do anything specific to get it to pair in Wii U mode? I can't get it to pair at all.

My stdout looks mostly the same:

```
Unsupported manufacturer
Failed to set device address
Device manufacturer: Realtek Semiconductor Corporation (93)
Failed to set device address
Warning: device address must have a Nintendo OUI
Can't write simple pairing mode: Input/output error (5)
Failed to set simple pairing mode
Warning: make sure secure simple pairing mode is disabled
listening for connections... (press wii's sync button)
```

And I, too, use the JRogaishio/WiimoteEmulator fork (with [additional patch to fix build issues](https://github.com/JRogaishio/WiimoteEmulator/pull/2)), and executing `sudo hciconfig hci0 reset` as suggested in https://github.com/JRogaishio/WiimoteEmulator/pull/1#issuecomment-1878825599 didn't help.
